from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(513, 340)
        Dialog.setMinimumSize(QtCore.QSize(513, 340))
        Dialog.setMaximumSize(QtCore.QSize(513, 340))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.Img = QtWidgets.QLabel(Dialog)
        self.Img.setMinimumSize(QtCore.QSize(150, 150))
        self.Img.setMaximumSize(QtCore.QSize(150, 150))
        self.Img.setText("")
        self.Img.setPixmap(QtGui.QPixmap("Icon/Connect_sever.png"))
        self.Img.setScaledContents(True)
        self.Img.setObjectName("Img")
        self.gridLayout_2.addWidget(self.Img, 0, 0, 1, 1)
        self.SingIn = QtWidgets.QGroupBox(Dialog)
        self.SingIn.setMinimumSize(QtCore.QSize(321, 281))
        self.SingIn.setMaximumSize(QtCore.QSize(321, 281))
        self.SingIn.setObjectName("SingIn")
        self.gridLayout = QtWidgets.QGridLayout(self.SingIn)
        self.gridLayout.setContentsMargins(20, -1, -1, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_text_info = QtWidgets.QLabel(self.SingIn)
        self.label_text_info.setObjectName("label_text_info")
        self.gridLayout.addWidget(self.label_text_info, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.Pass_layout = QtWidgets.QHBoxLayout()
        self.Pass_layout.setContentsMargins(5, -1, -1, -1)
        self.Pass_layout.setSpacing(10)
        self.Pass_layout.setObjectName("Pass_layout")
        self.label_Password = QtWidgets.QLabel(self.SingIn)
        self.label_Password.setObjectName("label_Password")
        self.Pass_layout.addWidget(self.label_Password)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.SingIn)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.Pass_layout.addWidget(self.lineEdit_Password)
        self.label = QtWidgets.QLabel(self.SingIn)
        self.label.setObjectName("label")
        self.Pass_layout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.SingIn)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.Pass_layout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.Pass_layout, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 2)
        self.User_layout = QtWidgets.QHBoxLayout()
        self.User_layout.setContentsMargins(5, -1, -1, -1)
        self.User_layout.setSpacing(7)
        self.User_layout.setObjectName("User_layout")
        self.label_Username = QtWidgets.QLabel(self.SingIn)
        self.label_Username.setObjectName("label_Username")
        self.User_layout.addWidget(self.label_Username)
        self.lineEdit_Username = QtWidgets.QLineEdit(self.SingIn)
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Username.setFocus()
        self.User_layout.addWidget(self.lineEdit_Username)
        self.gridLayout.addLayout(self.User_layout, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SingIn, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SingIn.setTitle(_translate("Dialog", "Connect To sever"))
        self.label_text_info.setText(_translate("Dialog", "Insert Username and IP Server"))
        self.label_Password.setText(_translate("Dialog", "IP Server:"))
        self.label.setText(_translate("Dialog", "Port:"))
        self.label_Username.setText(_translate("Dialog", "Username:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
